name: Build

on:
  push:
    tags:
      - 'v*' # Trigger only on version tags
  pull_request:

jobs:
  build-windows-i386:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Build windows-i386
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T release --32bits
        ./waf.bat build
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-i386-build
        path: build/output/ # Adjust the path to your artifact location

  build-windows-amd64:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Build windows-amd64
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T release
        ./waf.bat build
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-amd64-build
        path: build/output/ # Adjust the path to your artifact location

  build-dedicated-windows-i386:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Build dedicated windows-i386
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T release -d --32bits
        ./waf.bat build
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: dedicated-windows-i386-build
        path: build/output/ # Adjust the path to your artifact location

  build-dedicated-windows-amd64:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Build dedicated windows-amd64
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T release -d
        ./waf.bat build
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: dedicated-windows-amd64-build
        path: build/output/ # Adjust the path to your artifact location
