name: Build

on: [push, pull_request]

jobs:

  build-windows-i386:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Build windows-i386
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T debug --32bits
        ./waf.bat build
    - name: Upload windows-i386 build
      uses: actions/upload-artifact@v2
      with:
        name: windows-i386-build
        path: build/

  build-windows-amd64:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Build windows-amd64
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T debug
        ./waf.bat build
    - name: Upload windows-amd64 build
      uses: actions/upload-artifact@v2
      with:
        name: windows-amd64-build
        path: build/

  build-dedicated-windows-i386:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Build dedicated windows-i386
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T debug -d
        ./waf.bat build
    - name: Upload dedicated windows-i386 build
      uses: actions/upload-artifact@v2
      with:
        name: dedicated-windows-i386-build
        path: build/

  build-dedicated-windows-amd64:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Build dedicated windows-amd64
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T debug -d
        ./waf.bat build
    - name: Upload dedicated windows-amd64 build
      uses: actions/upload-artifact@v2
      with:
        name: dedicated-windows-amd64-build
        path: build/
