on: [push, pull_request]

jobs:

  build-windows-i386:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
    - name: Build windows-i386
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T debug --32bits
        ./waf.bat build
    - name: Upload Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: windows-i386-artifact
        path: ./build  # Replace './build' with the actual output directory if different

  build-windows-amd64:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
    - name: Build windows-amd64
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T debug
        ./waf.bat build
    - name: Upload Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: windows-amd64-artifact
        path: ./build  # Replace './build' with the actual output directory if different

  build-dedicated-windows-i386:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
    - name: Build dedicated windows-i386
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T debug -d
        ./waf.bat build
    - name: Upload Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: dedicated-windows-i386-artifact
        path: ./build  # Replace './build' with the actual output directory if different

  build-dedicated-windows-amd64:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
    - name: Build dedicated windows-amd64
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T debug -d
        ./waf.bat build
    - name: Upload Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: dedicated-windows-amd64-artifact
        path: ./build  # Replace './build' with the actual output directory if different
