name: Tests

on: [push, pull_request]

jobs:

  tests-windows-i386:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Run tests windows-i386
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T release --tests --prefix=out/ --32bits
        ./waf.bat install
        cd out
        $env:Path = "bin";
        ./unittest.exe

  tests-windows-amd64:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Run tests windows-amd64
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T release --tests --prefix=out/
        ./waf.bat install
        cd out
        $env:Path = "bin";
        ./unittest.exe
